version: '3'

services:
  db_setup:
    environment:
      - TZ=Europe/Warsaw
    build:
      context: ../backend-database
      dockerfile: db_setup.Dockerfile
    volumes:
      - ../backend-database/tablica.db:/usr/local/app/tablica.db

  db_refresh:
    depends_on:
      - db_setup
    environment:
      - TZ=Europe/Warsaw
    build:
      context: ../backend-database
      dockerfile: db.Dockerfile
    volumes:
      - ../backend-database/tablica.db:/usr/local/app/tablica.db

  backend:
    depends_on:
      - db_refresh
    environment:
      - TZ=Europe/Warsaw
    build:
      context: ../backend-database
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend-database/tablica.db:/usr/local/app/tablica.db

  frontend:
    depends_on:
      - backend
    environment:
      - TZ=Europe/Warsaw
    build:
      context: ../timetable-web
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
